{% set name = "mkdocs-git-committers-plugin-2" %}
{% set version = "2.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: a01f17369e79ca28651681cddf212770e646e6191954bad884ca3067316aae60

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }},<4.0
    - mkdocs >=1.0.3
    - requests
    - gitpython

test:
  imports:
    - mkdocs_git_committers_plugin_2
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/ojacques/mkdocs-git-committers-plugin-2/
  summary: An MkDocs plugin to create a list of contributors on the page. The git-committers plugin will seed the template context with a list of GitHub or GitLab committers and other useful GIT info such as last modified date
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pavelzw
