{% set name = "mkdocs-git-committers-plugin-2" %}
{% set version = "2.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mkdocs-git-committers-plugin-2-{{ version }}.tar.gz
  sha256: 87a241624116e1c6245034ca2ee3f247e4500589e75f19f71d352b052a8630d8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8,<4.0
    - pip
  run:
    - python >=3.8,<4.0
    - mkdocs >=1.0.3
    - requests
    - gitpython

test:
  imports:
    - mkdocs_git_committers_plugin_2
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ojacques/mkdocs-git-committers-plugin-2/
  summary: An MkDocs plugin to create a list of contributors on the page. The git-committers plugin will seed the template context with a list of GitHub or GitLab committers and other useful GIT info such as last modified date
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pavelzw
