schema_version: 1

context:
  name: mkdocs-git-committers-plugin-2
  version: 2.5.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name | replace('-', '_') }}-${{ version }}.tar.gz
  sha256: a01f17369e79ca28651681cddf212770e646e6191954bad884ca3067316aae60

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }},<4.0
    - mkdocs >=1.0.3
    - requests
    - gitpython

tests:
  - python:
      imports:
        - mkdocs_git_committers_plugin_2
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - pip check

about:
  summary: An MkDocs plugin to create a list of contributors on the page. The git-committers plugin will seed the template context with a list of GitHub or GitLab committers and other useful GIT info such as last modified date
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/ojacques/mkdocs-git-committers-plugin-2/

extra:
  recipe-maintainers:
    - pavelzw
